/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataPointDto } from '../models/DataPointDto';
import { RepoDataJobDto } from '../models/RepoDataJobDto';
import { RepoPointDto } from '../models/RepoPointDto';
import { HttpFile } from '../http/http';

export class AutoJobConfigDto {
    'dataPoint'?: DataPointDto;
    'repoPoint'?: RepoPointDto;
    'name'?: string | null;
    'createdBy'?: string | null;
    'lastRan'?: Date | null;
    'cronSchedule'?: string | null;
    'backupPath'?: string | null;
    'nextRun'?: Date | null;
    'dateCreated'?: Date;
    'pastJobs'?: Array<RepoDataJobDto> | null;
    'currentJob'?: RepoDataJobDto;
    'isRunning'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataPoint",
            "baseName": "dataPoint",
            "type": "DataPointDto",
            "format": ""
        },
        {
            "name": "repoPoint",
            "baseName": "repoPoint",
            "type": "RepoPointDto",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastRan",
            "baseName": "lastRan",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "cronSchedule",
            "baseName": "cronSchedule",
            "type": "string",
            "format": ""
        },
        {
            "name": "backupPath",
            "baseName": "backupPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextRun",
            "baseName": "nextRun",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "pastJobs",
            "baseName": "pastJobs",
            "type": "Array<RepoDataJobDto>",
            "format": ""
        },
        {
            "name": "currentJob",
            "baseName": "currentJob",
            "type": "RepoDataJobDto",
            "format": ""
        },
        {
            "name": "isRunning",
            "baseName": "isRunning",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutoJobConfigDto.attributeTypeMap;
    }

    public constructor() {
    }
}
