/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CPUItemDto {
    'cpu'?: string | null;
    'userPercent'?: number;
    'nicePercent'?: number;
    'systemPercent'?: number;
    'ioWaitPercent'?: number;
    'irqPercent'?: number;
    'softPercent'?: number;
    'stealPercent'?: number;
    'guestPercent'?: number;
    'idlePercent'?: number;
    'usedPercent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "string",
            "format": ""
        },
        {
            "name": "userPercent",
            "baseName": "userPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "nicePercent",
            "baseName": "nicePercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "systemPercent",
            "baseName": "systemPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "ioWaitPercent",
            "baseName": "ioWaitPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "irqPercent",
            "baseName": "irqPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "softPercent",
            "baseName": "softPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "stealPercent",
            "baseName": "stealPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "guestPercent",
            "baseName": "guestPercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "idlePercent",
            "baseName": "idlePercent",
            "type": "number",
            "format": "double"
        },
        {
            "name": "usedPercent",
            "baseName": "usedPercent",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return CPUItemDto.attributeTypeMap;
    }

    public constructor() {
    }
}
