/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DataPointDto {
    'userName': string;
    'pointName': string;
    'pointId'?: string;
    'maxBytes'?: number;
    'usedBytes'?: number;
    'freeBytes'?: number;
    'lastAccessed'?: Date | null;
    'isRepository'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "pointName",
            "baseName": "pointName",
            "type": "string",
            "format": ""
        },
        {
            "name": "pointId",
            "baseName": "pointId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "maxBytes",
            "baseName": "maxBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "usedBytes",
            "baseName": "usedBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "freeBytes",
            "baseName": "freeBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lastAccessed",
            "baseName": "lastAccessed",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isRepository",
            "baseName": "isRepository",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DataPointDto.attributeTypeMap;
    }

    public constructor() {
    }
}
