/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FileDto {
    'accessDate'?: Date;
    'modifyDate'?: Date;
    'createDate'?: Date;
    'sizeBytes'?: number | null;
    'name'?: string | null;
    'path'?: string | null;
    'isDirectory'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessDate",
            "baseName": "accessDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifyDate",
            "baseName": "modifyDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "sizeBytes",
            "baseName": "sizeBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDirectory",
            "baseName": "isDirectory",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileDto.attributeTypeMap;
    }

    public constructor() {
    }
}
