/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FilePutDto {
    'path'?: string | null;
    'newPath'?: string | null;
    'base64Content'?: string | null;
    'isDirectory'?: boolean;
    'copy'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "newPath",
            "baseName": "newPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "base64Content",
            "baseName": "base64Content",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDirectory",
            "baseName": "isDirectory",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "copy",
            "baseName": "copy",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilePutDto.attributeTypeMap;
    }

    public constructor() {
    }
}
