/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FileOutputDto {
    'path'?: string | null;
    'data'?: string | null;
    'isGZIP'?: boolean;
    'isBase64'?: boolean;
    'isDirectory'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "isGZIP",
            "baseName": "isGZIP",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isBase64",
            "baseName": "isBase64",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDirectory",
            "baseName": "isDirectory",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileOutputDto.attributeTypeMap;
    }

    public constructor() {
    }
}
