/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GlobalConfigPutDto {
    'repoBaseDirectory'?: string | null;
    'dataBaseDirectory'?: string | null;
    'logBaseDirectory'?: string | null;
    'mountBaseDirectory'?: string | null;
    'serverSmtpUrl'?: string | null;
    'serverEmailAddress'?: string | null;
    'serverEmailPassword'?: string | null;
    'authMins'?: number | null;
    'maxBytesPerUser'?: number | null;
    'maxRequestsPerUser'?: number | null;
    'rateLimitResetMins'?: number | null;
    'rollingSecret'?: string | null;
    'overwriteNulls'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "repoBaseDirectory",
            "baseName": "repoBaseDirectory",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataBaseDirectory",
            "baseName": "dataBaseDirectory",
            "type": "string",
            "format": ""
        },
        {
            "name": "logBaseDirectory",
            "baseName": "logBaseDirectory",
            "type": "string",
            "format": ""
        },
        {
            "name": "mountBaseDirectory",
            "baseName": "mountBaseDirectory",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverSmtpUrl",
            "baseName": "serverSmtpUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverEmailAddress",
            "baseName": "serverEmailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverEmailPassword",
            "baseName": "serverEmailPassword",
            "type": "string",
            "format": ""
        },
        {
            "name": "authMins",
            "baseName": "authMins",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxBytesPerUser",
            "baseName": "maxBytesPerUser",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRequestsPerUser",
            "baseName": "maxRequestsPerUser",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "rateLimitResetMins",
            "baseName": "rateLimitResetMins",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "rollingSecret",
            "baseName": "rollingSecret",
            "type": "string",
            "format": ""
        },
        {
            "name": "overwriteNulls",
            "baseName": "overwriteNulls",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GlobalConfigPutDto.attributeTypeMap;
    }

    public constructor() {
    }
}
