/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobRestoreDto {
    'fromRepo'?: string | null;
    'toData'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromRepo",
            "baseName": "fromRepo",
            "type": "string",
            "format": ""
        },
        {
            "name": "toData",
            "baseName": "toData",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobRestoreDto.attributeTypeMap;
    }

    public constructor() {
    }
}
