/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MessageReadItem } from '../models/MessageReadItem';
import { HttpFile } from '../http/http';

export class MessageItemDto {
    'id'?: string;
    'fromUser'?: string | null;
    'toUsers'?: Array<string> | null;
    'subject'?: string | null;
    'text'?: string | null;
    'highPriority'?: boolean;
    'dateSent'?: Date;
    'readBy'?: Array<MessageReadItem> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "fromUser",
            "baseName": "fromUser",
            "type": "string",
            "format": ""
        },
        {
            "name": "toUsers",
            "baseName": "toUsers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "highPriority",
            "baseName": "highPriority",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dateSent",
            "baseName": "dateSent",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "readBy",
            "baseName": "readBy",
            "type": "Array<MessageReadItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MessageItemDto.attributeTypeMap;
    }

    public constructor() {
    }
}
