/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RepoPointShareDto {
    'userName'?: string | null;
    'canRead'?: boolean;
    'canWrite'?: boolean;
    'canShare'?: boolean;
    'canManage'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "canRead",
            "baseName": "canRead",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWrite",
            "baseName": "canWrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canShare",
            "baseName": "canShare",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canManage",
            "baseName": "canManage",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RepoPointShareDto.attributeTypeMap;
    }

    public constructor() {
    }
}
