/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RepoDataJobSummaryDto {
    'jobId'?: string;
    'filesNew'?: number;
    'filesChanged'?: number;
    'filesUnmodified'?: number;
    'dirsNew'?: number;
    'dirsChanged'?: number;
    'dirsUnmodified'?: number;
    'dataBlobs'?: number;
    'treeBlobs'?: number;
    'dataAdded'?: number;
    'dataAddedPacked'?: number;
    'totalFilesProcessed'?: number;
    'totalBytesProcessed'?: number;
    'totalDuration'?: number;
    'snapshotId'?: string | null;
    'lastUpdated'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "filesNew",
            "baseName": "filesNew",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filesChanged",
            "baseName": "filesChanged",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filesUnmodified",
            "baseName": "filesUnmodified",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dirsNew",
            "baseName": "dirsNew",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dirsChanged",
            "baseName": "dirsChanged",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dirsUnmodified",
            "baseName": "dirsUnmodified",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dataBlobs",
            "baseName": "dataBlobs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "treeBlobs",
            "baseName": "treeBlobs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dataAdded",
            "baseName": "dataAdded",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "dataAddedPacked",
            "baseName": "dataAddedPacked",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalFilesProcessed",
            "baseName": "totalFilesProcessed",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalBytesProcessed",
            "baseName": "totalBytesProcessed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalDuration",
            "baseName": "totalDuration",
            "type": "number",
            "format": "double"
        },
        {
            "name": "snapshotId",
            "baseName": "snapshotId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RepoDataJobSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}
