/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataPointDto } from '../models/DataPointDto';
import { JobErrorDto } from '../models/JobErrorDto';
import { RepoDataJobStatusDto } from '../models/RepoDataJobStatusDto';
import { RepoDataJobSummaryDto } from '../models/RepoDataJobSummaryDto';
import { RepoPointDto } from '../models/RepoPointDto';
import { HttpFile } from '../http/http';

export class RepoDataJobDto {
    'jobId'?: string;
    'dataPoint'?: DataPointDto;
    'repoPoint'?: RepoPointDto;
    'createDate'?: Date;
    'startDate'?: Date | null;
    'endDate'?: Date | null;
    'jobType'?: string | null;
    'startedBy'?: string | null;
    'isRunning'?: boolean;
    'fromPath'?: string | null;
    'toPath'?: string | null;
    'summary'?: RepoDataJobSummaryDto;
    'lastStatus'?: RepoDataJobStatusDto;
    'restoreSnapshotId'?: string | null;
    'errors'?: Array<JobErrorDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "dataPoint",
            "baseName": "dataPoint",
            "type": "DataPointDto",
            "format": ""
        },
        {
            "name": "repoPoint",
            "baseName": "repoPoint",
            "type": "RepoPointDto",
            "format": ""
        },
        {
            "name": "createDate",
            "baseName": "createDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "jobType",
            "baseName": "jobType",
            "type": "string",
            "format": ""
        },
        {
            "name": "startedBy",
            "baseName": "startedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "isRunning",
            "baseName": "isRunning",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fromPath",
            "baseName": "fromPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "toPath",
            "baseName": "toPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "RepoDataJobSummaryDto",
            "format": ""
        },
        {
            "name": "lastStatus",
            "baseName": "lastStatus",
            "type": "RepoDataJobStatusDto",
            "format": ""
        },
        {
            "name": "restoreSnapshotId",
            "baseName": "restoreSnapshotId",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<JobErrorDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RepoDataJobDto.attributeTypeMap;
    }

    public constructor() {
    }
}
