/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RepoDataJobStatusDto {
    'jobId'?: string;
    'secondsElapsed'?: number;
    'secondsRemaining'?: number;
    'percentDone'?: number;
    'totalFiles'?: number;
    'filesDone'?: number;
    'totalBytes'?: number;
    'bytesDone'?: number;
    'errorCount'?: number;
    'currentFiles'?: Array<string> | null;
    'lastUpdated'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "secondsElapsed",
            "baseName": "secondsElapsed",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "secondsRemaining",
            "baseName": "secondsRemaining",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "percentDone",
            "baseName": "percentDone",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalFiles",
            "baseName": "totalFiles",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filesDone",
            "baseName": "filesDone",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalBytes",
            "baseName": "totalBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "bytesDone",
            "baseName": "bytesDone",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "errorCount",
            "baseName": "errorCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "currentFiles",
            "baseName": "currentFiles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RepoDataJobStatusDto.attributeTypeMap;
    }

    public constructor() {
    }
}
