/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CPUItemDto } from '../models/CPUItemDto';
import { HttpFile } from '../http/http';

export class SystemStatusDto {
    'cpus'?: Array<CPUItemDto> | null;
    'apiUptime'?: string | null;
    'systemUptime'?: string | null;
    'apiVersion'?: string | null;
    'kernelVersion'?: string | null;
    'totalUsersRegistered'?: number | null;
    'totalDataPoints'?: number | null;
    'totalRepoPoints'?: number | null;
    'maxDataBytes'?: number | null;
    'maxRepoBytes'?: number | null;
    'allocatedDataBytes'?: number | null;
    'allocatedRepoBytes'?: number | null;
    'totalJobs'?: number | null;
    'totalRunningJobs'?: number | null;
    'freeDataBytes'?: number | null;
    'freeRepoBytes'?: number | null;
    'averageCpu'?: CPUItemDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cpus",
            "baseName": "cpus",
            "type": "Array<CPUItemDto>",
            "format": ""
        },
        {
            "name": "apiUptime",
            "baseName": "apiUptime",
            "type": "string",
            "format": "date-span"
        },
        {
            "name": "systemUptime",
            "baseName": "systemUptime",
            "type": "string",
            "format": "date-span"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "kernelVersion",
            "baseName": "kernelVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalUsersRegistered",
            "baseName": "totalUsersRegistered",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalDataPoints",
            "baseName": "totalDataPoints",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalRepoPoints",
            "baseName": "totalRepoPoints",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxDataBytes",
            "baseName": "maxDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRepoBytes",
            "baseName": "maxRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "allocatedDataBytes",
            "baseName": "allocatedDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "allocatedRepoBytes",
            "baseName": "allocatedRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalJobs",
            "baseName": "totalJobs",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalRunningJobs",
            "baseName": "totalRunningJobs",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "freeDataBytes",
            "baseName": "freeDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "freeRepoBytes",
            "baseName": "freeRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "averageCpu",
            "baseName": "averageCpu",
            "type": "CPUItemDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemStatusDto.attributeTypeMap;
    }

    public constructor() {
    }
}
