/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AutoJobConfigDto } from '../models/AutoJobConfigDto';
import { DataPointDto } from '../models/DataPointDto';
import { RepoDataJobDto } from '../models/RepoDataJobDto';
import { RepoPointDto } from '../models/RepoPointDto';
import { HttpFile } from '../http/http';

export class UserSummaryDto {
    'userName'?: string | null;
    'dateCreated'?: Date;
    'lastLogin'?: Date | null;
    'emailAddress'?: string | null;
    'maxDataBytes'?: number;
    'maxRepoBytes'?: number;
    'apiCalls'?: number | null;
    'apiBytes'?: number | null;
    'apiLastCall'?: Date | null;
    'usedDataBytes'?: number;
    'usedRepoBytes'?: number;
    'freeDataBytes'?: number;
    'freeRepoBytes'?: number;
    'permissions'?: Array<string> | null;
    'allJobs'?: Array<RepoDataJobDto> | null;
    'dataPoints'?: Array<DataPointDto> | null;
    'repoPoints'?: Array<RepoPointDto> | null;
    'autoJobs'?: Array<AutoJobConfigDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastLogin",
            "baseName": "lastLogin",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxDataBytes",
            "baseName": "maxDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRepoBytes",
            "baseName": "maxRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "apiCalls",
            "baseName": "apiCalls",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "apiBytes",
            "baseName": "apiBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "apiLastCall",
            "baseName": "apiLastCall",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "usedDataBytes",
            "baseName": "usedDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "usedRepoBytes",
            "baseName": "usedRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "freeDataBytes",
            "baseName": "freeDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "freeRepoBytes",
            "baseName": "freeRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "allJobs",
            "baseName": "allJobs",
            "type": "Array<RepoDataJobDto>",
            "format": ""
        },
        {
            "name": "dataPoints",
            "baseName": "dataPoints",
            "type": "Array<DataPointDto>",
            "format": ""
        },
        {
            "name": "repoPoints",
            "baseName": "repoPoints",
            "type": "Array<RepoPointDto>",
            "format": ""
        },
        {
            "name": "autoJobs",
            "baseName": "autoJobs",
            "type": "Array<AutoJobConfigDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}
