/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserPermissionDto {
    'permission'?: string | null;
    'allowed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "permission",
            "baseName": "permission",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowed",
            "baseName": "allowed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserPermissionDto.attributeTypeMap;
    }

    public constructor() {
    }
}
