/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserCreateDto {
    'userName': string;
    'password': string;
    'emailAddress': string;
    'isPrivate': boolean;
    'maxDataBytes': number;
    'maxRepoBytes': number;
    'permissions'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPrivate",
            "baseName": "isPrivate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxDataBytes",
            "baseName": "maxDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRepoBytes",
            "baseName": "maxRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserCreateDto.attributeTypeMap;
    }

    public constructor() {
    }
}
