/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserPutDto {
    'emailAddress'?: string | null;
    'isPrivate'?: boolean | null;
    'maxDataBytes'?: number | null;
    'maxRepoBytes'?: number | null;
    'password'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPrivate",
            "baseName": "isPrivate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxDataBytes",
            "baseName": "maxDataBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRepoBytes",
            "baseName": "maxRepoBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserPutDto.attributeTypeMap;
    }

    public constructor() {
    }
}
