/**
 * Neptis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WSNotificationDto {
    'id'?: string;
    'sendTo'?: string | null;
    'actionBy'?: string | null;
    'result'?: string | null;
    'type'?: string | null;
    'subject'?: string | null;
    'description'?: string | null;
    'dateSent'?: Date;
    'isRead'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sendTo",
            "baseName": "sendTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "actionBy",
            "baseName": "actionBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateSent",
            "baseName": "dateSent",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isRead",
            "baseName": "isRead",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WSNotificationDto.attributeTypeMap;
    }

    public constructor() {
    }
}
